### ISSUE TITLE
De opdracht beschrijven

### ISSUE THREAD

**Issue by hesteren** [hesteren/statuspagina-monta#4]
## Task
De opdracht beschrijven om meer duidelijkheid te creëren

- [ ] Een kernachtige formulering van de verstrekte stageopdracht
- [ ] De kwestie
- [ ] Welk concreet businessdoel wil de opdrachtgever bereiken
- [ ] De doelstelling van de opdracht
- [ ] Beschrijving van de projectgrenzen (afbakenen)
- [ ] Welke oplossingsrichting wordt er gekozen
- [ ] Het soort opdracht (product)
- [ ] De eind- en tussenproducten
- [ ] De gekozen projectmethode (agile)
- [ ] Hoofdvraag en deelvragen
