### ISSUE TITLE
Planning en organisatie

### ISSUE THREAD

**Issue by hesteren** [hesteren/statuspagina-monta#8]
## Task
Planning en organisatie hoofdstuk schrijven om een goede planning duidelijk te krijgen

- [x] Beschrijving van de gekozen projectorganisatie
- [x] Projectactiviteiten
- [x] Prioriteiten stellen (MoSCoW)
- [x] Risico's
- [x] Eventuele vertrouwelijkheids- en geheimhoudingsaspecten
